services:
  - type: web
    name: omolrelay
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:8000 parnya:app

  - type: worker
    name: keepalive
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ping.py
