services:
  - type: web
    name: omolrelay
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn parnya:app --bind 0.0.0.0:$PORT"
  - type: worker
    name: keepalive
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ping.py"
